module.exports = [
  {
    title: "Pet Paradise",
    description:
      "Simple CRUD application built with Django, designed to facilitate the adoption of animals",
    prodLink: null,
    githubLink: "https://github.com/cassius2828/pet-pal-paradise--django-lab",
    technologies: [
      {
        name: "Django",
        icon: "faHTML",
      },
      {
        name: "Python",
        icon: "faPython",
      },
      {
        name: "Postgres",
        icon: "faElephant",
      },
    ],
    featured: false,
    img: null,
  },
  {
    title: "Cat Collector",
    description:
      "CRUD application built with Django, allowing users to interact with some cool cats.",
    prodLink: null,
    githubLink: "https://github.com/cassius2828/cat-collector",
    technologies: [
      {
        name: "Django",
        icon: "faHTML",
      },
      {
        name: "Python",
        icon: "faPython",
      },
      {
        name: "Postgres",
        icon: "faElephant",
      },
    ],
    featured: false,
    img: null,
  },
  {
    title: "Curate Sphere",
    description:
      "CurateSphere is a PERN stack (PostgreSQL, Express, React, Node.js) CRUD application that leverages the Harvard Art Museums API to allow users to create and manage their own art exhibitions, featuring artworks curated from the API. Efforts include complex search filtering, advanced state management, custom caching system integration, customizable profiles, end to end testing, and robust error handling",
    githubLink: "https://github.com/cassius2828/curate-sphere",
    prodLink: "https://curate-sphere.netlify.app/",
    technologies: [
      {
        name: "React",
        icon: "faReact",
      },
      {
        name: "Node JS",
        icon: "faNodeJs",
      },
      {
        name: "Vite",
        icon: "faBolt",
      },
      {
        name: "Tailwindcss",
        icon: "faWind",
      },
      {
        name: "Postgres",
        icon: "faElephant",
      },
      {
        name: "Cypress",
        icon: "faFlaskVial",
      },
    ],
    featured: true,
    img: "https://imglocation",
  },
  {
    title: "Sommelier Circle",
    description:
      "This is a full-stack MERN (MongoDB, Express, React, Node.js) application designed to foster a vibrant and engaging online wine community. Users can create and manage blog posts through a rich text editor (Quill), connect with other wine enthusiasts, and explore an extensive wine encyclopedia. Additionally, users can discover new wines through a custom API, explore wine-related events, and utilize advanced features such as the following:\n\n" +
      "Inverted Index with Fuzzy Search: A powerful search functionality that provides an enhanced experience when exploring wines, critics, and wine-related events.\n" +
      "Google Places API Integration: Tailored wine location suggestions are delivered through a seamless integration with the Google Places API, allowing users to explore venues and wineries near them.\n" +
      "Autocomplete Feature for Venue Search: Autocomplete functionality assists users in finding wine venues near their location quickly and efficiently.\n\n" +
      "Users can also follow friends, interact with the community, and participate in wine-related events. All content, including images and descriptions, is for demonstration purposes and is not owned by the creators. The data generated by the app should not be considered over authenticated wine APIs.",
    githubLink: "https://github.com/cassius2828/sommelier-circle-frontend",
    prodLink: "https://sommelier-circle.netlify.app/",
    technologies: [
      {
        name: "React",
        icon: "faReact",
      },
      {
        name: "Node JS",
        icon: "faNodeJs",
      },
      {
        name: "Vite",
        icon: "faBolt",
      },
      {
        name: "Tailwindcss",
        icon: "faWind",
      },
      {
        name: "MongoDB",
        icon: "faLeaf",
      },
    ],
    featured: true,
    img: "https://imglocation",
  },
  {
    title: "Lineup Legends",
    description: `
Lineup Legends is an engaging fantasy basketball platform that allows users to create and manage their dream teams within a $15 budget, choosing from over 200 unique players. Users can share their lineups, upvote others, and participate in a rating system to foster community engagement. With strategic player trades and social features like a friend system and comments, Lineup Legends enhances the fantasy basketball experience. Built with a robust tech stack including MongoDB, Express.js, and Node.js, the platform also plans future enhancements like social media sharing and mobile responsiveness. Join Lineup Legends to showcase your strategic prowess and connect with fellow basketball enthusiasts!

`,
    githubLink: "https://github.com/cassius2828/Lineup-Legends",
    prodLink: "https://lineup-legends-5bdbc4813272.herokuapp.com/",
    technologies: [
      {
        name: "Node JS",
        icon: "faNodeJs",
      },

      {
        name: "Sass",
        icon: "faSass",
      },
      {
        name: "MongoDB",
        icon: "faLeaf",
      },
    ],
    featured: true,
    img: "https://imglocation",
  },
  // TODO | Get code from gitlab
  {
    title: "Max Protection Moving",
    description:
      "Landing page for a moving company that includes custom logic for a quote calculator using the google places api to track distance along with other factors from the forms to come up with ball park numbers for a client's potential move. ",
    prodLink: "https://max-protection-moving.netlify.app/",
    githubLink: "https://gitlab.com/cassius.reynolds/max-protection-moving",
    technologies: [
      {
        name: "React",
        icon: "faReact",
      },
      {
        name: "Tailwindcss",
        icon: "faWind",
      },
      {
        name: "Vite",
        icon: "faBolt",
      },
    ],
    featured: false,
    img: null,
  },
  // TODO | Get code from gitlab
  {
    title: "Place of Grace Inc",
    description:
      "Webiste created to give information about a care home facility for developmentally disabled adults in Northen California. Includes about pages, staff directory, mission page, careers page, contact page, and more. Forms are sent to specific staff via microsoft graph api. This real-world project gave me experience in DNS configuration, SEO, and working with a cloud infrastructure via a graph api and utilizing OAuth systems.",
    prodLink: "https://placeofgrace.net/",
    githubLink: "https://gitlab.com/placeofgrace/pog-frontend",
    technologies: [
      {
        name: "React",
        icon: "faReact",
      },
      {
        name: "Sass",
        icon: "faSass",
      },
      {
        name: "Vite",
        icon: "faBolt",
      },
    ],
    featured: false,
    img: null,
  },
  // TODO | Get code from gitlab
  {
    title: "Fast and Easy Solar",
    description:
      "Landing page for a solar partered business who's goal is to assist buyers in determining which programs they are qualified for and connecting them to the proper businesses and facilitating the transaction. This applicaiton uses emailjs for sending custom email templates to the owner and calendy intergration to manage appointments. There are several sections of the website available to give information to the user. All design aspects were created by me on the request / guidance of the client.",
    prodLink: "https://fastandeasysolar.netlify.app/",
    githubLink: "https://gitlab.com/cassius.reynolds/fastandeasysolar",
    technologies: [
      {
        name: "Tailwindcss",
        icon: "faWind",
      },
      {
        name: "React",
        icon: "faReact",
      },
      {
        name: "Vite",
        icon: "faBolt",
      },
    ],
    featured: false,
    img: null,
  },
  // TODO | add later
  // {
  //   title: "Internal War | E-commerce Store",
  //   description:
  //     "Simple CRUD application built with Django, designed to facilitate the adoption of animals",
  //   prodLink: null,
  //   githubLink: "https://github.com/cassius2828/pet-pal-paradise--django-lab",
  //   technologies: [
  //     {
  //       name: "Remix",
  //       icon: "faRemix",
  //     },
  //     {
  //       name: "Hydrogen",
  //       icon: "faHydrogen",
  //     },
  //     {
  //       name: "Shopify",
  //       icon: "faShopify",
  //     },
  //   ],
  //   featured: false,
  //   img: null,
  // },
  // TODO | add later
  // {
  //   title: "Taydada Plates",
  //   description:
  //     "Simple CRUD application built with Django, designed to facilitate the adoption of animals",
  //   prodLink: null,
  //   githubLink: "https://github.com/cassius2828/pet-pal-paradise--django-lab",
  //   technologies: [
  //     {
  //       name: "Django",
  //       icon: "faPython",
  //     },
  //     {
  //       name: "Python",
  //       icon: "faPython",
  //     },
  //     {
  //       name: "Postgres",
  //       icon: "faElephant",
  //     },
  //   ],
  //   featured: false,
  //   img: null,
  // },

  {
    title: "Memory Squares",
    description: `Memory Game - Inspired by Nickelodeon's Brain Surge is a fun and challenging memory game where players must replicate a sequence of flashing squares generated by the CPU. As the game progresses, the grid size and difficulty increase with each level. Players click on the squares in the correct order and submit their sequence, which is compared to the CPU's. If correct, they advance; if wrong, the game ends. High scores are saved in local storage, and audio-visual feedback enhances the gameplay. The game uses arrays to store sequences, a timer for added challenge, and local storage to track and update high scores.`,
    prodLink: "https://cassius2828.github.io/memory-squares/",
    githubLink: "https://github.com/cassius2828/memory-squares",
    technologies: [
      {
        name: "Javascript",
        icon: "faJavascript",
      },
    ],
    featured: false,
    img: null,
  },
  {
    title: "Citrus Sun",
    description: `Simple and responsive layout for a landing page of a tech news site. This was a challenge where you are given a visual example and try to recreate it with your own code. This layout was created with flex-box in regular css.`,
    prodLink: "https://citrus-news-homepage.netlify.app/",
    githubLink: "https://github.com/cassius2828/news-homepage",
    technologies: [
      {
        name: "React",
        icon: "faReact",
      },
      {
        name: "CSS",
        icon: "faCSS",
      },
    ],
    featured: false,
    img: null,
  },
  {
    title: "Hawk Surf",
    description: `Responsive landing page created with bootstrap, sass, and html. There are multiple areas for the user to navigate to and learn about the company.`,
    prodLink: "https://hawk-surf.netlify.app/",
    githubLink: "https://github.com/cassius2828/Hawk-Surf",
    technologies: [
      {
        name: "Sass",
        icon: "faSass",
      },
      {
        name: "Bootstrap",
        icon: "faBootstrap",
      },
    ],
    featured: false,
    img: null,
  },
  {
    title: "Natours",
    description: `Responsive landing page created with sass and html. There are multiple areas for the user to navigate to and learn about the company.`,
    prodLink: "https://peaceful-wisp-0e1620.netlify.app/",
    githubLink: "https://github.com/cassius2828/natours",
    technologies: [
      {
        name: "Sass",
        icon: "faSass",
      },
      {
        name: "HTML",
        icon: "faHTML",
      },
    ],
    featured: false,
    img: null,
  },
];

// Lineup Legends is an engaging fantasy basketball platform that allows users to create and manage their dream teams within a $15 budget, choosing from over 200 unique players. Users can share their lineups, upvote others, and participate in a rating system to foster community engagement. With strategic player trades and social features like a friend system and comments, Lineup Legends enhances the fantasy basketball experience. Built with a robust tech stack including MongoDB, Express.js, and Node.js, the platform also plans future enhancements like social media sharing and mobile responsiveness. Join Lineup Legends to showcase your strategic prowess and connect with fellow basketball enthusiasts!
